version: '3.8'

services:
  tml-nft-bot:
    build: ./
    image: tml-nft-bot:${GITHUB_SHA}
    container_name: tml-nft-bot
    restart: always
    ports:
      - 127.0.0.1:8457:8000
    command:
      - bash
      - -c
      - |
        flask db init || true
        flask db migrate
        flask db upgrade
        gunicorn -b 0.0.0.0:8000 --statsd-host=statsd-exporter:9125 --statsd-prefix=tml_nft_bot -w 2 --timeout 10 --reload --preload app:app
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    secrets:
      - source: env-file
        target: /app/.env
    networks:
      - tml_network

#  statsd-exporter:
#    image: prom/statsd-exporter:v0.22.4
#    container_name: statsd-exporter
#    volumes:
#      - ./conf/statsd.conf:/statsd/statsd.conf
#    command:
#      - --statsd.mapping-config=/statsd/statsd.conf
#    networks:
#      - prometheus_back-tier
#      - tml_network

networks:
  tml_network:
#  prometheus_back-tier:
#    external: true

secrets:
  env-file:
    name: env-file-${GITHUB_SHA}
    file: ./.env
